[0m10:53:28.103166 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7796590780e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x779658f4e2d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x77965b15b890>]}


============================== 10:53:28.106311 | 21c2b155-fe92-4b39-9156-8e361a9bfad6 ==============================
[0m10:53:28.106311 [info ] [MainThread]: Running with dbt=1.9.4
[0m10:53:28.107021 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/codespace/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --select tag:staging', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m10:53:28.107603 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/analytics_engineering_curse/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:53:28.108618 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.058485556, "process_in_blocks": "0", "process_kernel_time": 0.104755, "process_mem_max_rss": "92640", "process_out_blocks": "8", "process_user_time": 1.293975}
[0m10:53:28.109177 [debug] [MainThread]: Command `dbt run` failed at 10:53:28.109052 after 0.06 seconds
[0m10:53:28.109629 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x779658e1a120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7796590780e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7796593ae840>]}
[0m10:53:28.110134 [debug] [MainThread]: Flushing usage events
[0m10:53:28.445523 [debug] [MainThread]: An error was encountered while trying to flush usage events
